name: Build APK

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install NDK & Platform
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
            "ndk;26.1.10909125" \
            "platforms;android-34" \
            "build-tools;34.0.0" \
            --sdk_root=$ANDROID_HOME

      - name: Build APK
        run: cd android && ./gradlew assembleDebug --no-daemon --no-build-cache

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: EasyWeb-Debug
          path: android/app/build/outputs/apk/debug/*.apk
